<a href="https://colab.research.google.com/github/Atharva-Bhole/Pytorch_Learning/blob/main/start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn
import matplotlib.pyplot as plt


torch.__version__

'2.5.1+cu121'

In [ ]:
weight = 0.7
bias = 0.3

start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim = 1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [ ]:
class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, dtype = torch.float), requires_grad = True)

    self.bias = nn.Parameter(torch.randn(1, dtype = torch.float), requires_grad = True)


  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

PyTorch tensors created using torch.Tensor()

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.Tensor([7,7])
vector

tensor([7., 7.])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.Tensor([[7,8],
                       [7,8]])

MATRIX

tensor([[7., 8.],
        [7., 8.]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.Tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to represent the data

In [ ]:
random_tensor = torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.8561, 0.4511, 0.4823, 0.1041],
        [0.2941, 0.9502, 0.1082, 0.0341],
        [0.8395, 0.7532, 0.3593, 0.1586]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones * random_tensor

tensor([[0.8561, 0.4511, 0.4823, 0.1041],
        [0.2941, 0.9502, 0.1082, 0.0341],
        [0.8395, 0.7532, 0.3593, 0.1586]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.range(0,10)

<ipython-input-29-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
onetoten = torch.arange(1,11)

In [ ]:
onetoten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype = torch.float64,
                            requires_grad = False,
                            device = None)
float_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [ ]:
float_16_tensor = float_tensor.type(torch.float16)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [ ]:
float_16_tensor.device

device(type='cpu')

In [ ]:
def get_tensor_dets(tensor):
  print(tensor)
  print(f"Datatype of tensor: {tensor.dtype}")
  print(f"Shape of tensor: {tensor.shape}")
  print(f"Device tensor is on: {tensor.device}")

In [ ]:
get_tensor_dets(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3])
Device tensor is on: cpu


In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5761, 0.0499, 0.4864, 0.0394],
        [0.2926, 0.9895, 0.8913, 0.0449],
        [0.8646, 0.0700, 0.7830, 0.4148]])

In [ ]:
random_tensor + 10

tensor([[10.5761, 10.0499, 10.4864, 10.0394],
        [10.2926, 10.9895, 10.8913, 10.0449],
        [10.8646, 10.0700, 10.7830, 10.4148]])

In [ ]:
T1 = random_tensor * 10

In [ ]:
random_tensor * T1

tensor([[3.3184, 0.0249, 2.3656, 0.0155],
        [0.8559, 9.7918, 7.9446, 0.0202],
        [7.4757, 0.0490, 6.1312, 1.7202]])

In [3]:
torch.matmul(torch.rand(3,1), torch.rand(1,3))

tensor([[0.3052, 0.3868, 0.0217],
        [0.2753, 0.3489, 0.0196],
        [0.6747, 0.8552, 0.0480]])

In [4]:
tensor_A = torch.rand(3,2)

In [5]:
tensor_A

tensor([[0.5656, 0.4718],
        [0.8631, 0.5209],
        [0.7683, 0.9747]])

In [6]:
tensor_A.T

tensor([[0.5656, 0.8631, 0.7683],
        [0.4718, 0.5209, 0.9747]])

In [7]:
tensor_A.shape, tensor_A.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

# Aggregation Functions in PyTorch

Finding min, max, mean, sum etc

In [8]:
x = torch.arange(0,100,10)

In [9]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [11]:
torch.max(x)

tensor(90)

In [12]:
x.max()

tensor(90)

In [14]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [15]:
x.type(torch.float32).mean()

tensor(45.)

In [16]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

## argmin() used to find out the index position of minimum value in the tensor

## argmax() used to find out the index position of max value in tensor

In [17]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

# Reshaping , Viewing and stacking tensors

## Reshaping, Stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze - removes all `1` dimensions from a tensor

* Unsqueeze - add a `1` dimension to a target tensor

* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [18]:
import torch
x = torch.arange(1., 10.)

In [19]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [22]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [23]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [24]:
x = torch.arange(1., 11.)

In [25]:
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [26]:
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [29]:
x_stacked = torch.stack([x,x,x,x])
x_stacked, x_stacked.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [30]:
# torch.squeeze() - removes all single dimensions from a tensor

In [36]:
x = torch.zeros(2,1,2,1,2)

In [37]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [38]:
y = torch.squeeze(x)

In [39]:
y.size(), x.size()

(torch.Size([2, 2, 2]), torch.Size([2, 1, 2, 1, 2]))

In [40]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [41]:
# torch.permute - rearranges tensor in specified order

x_original = torch.rand(size=(224,224,3))

In [42]:
x_permuted = x_original.permute(2,0,1)

In [43]:
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# PyTorch tensors and NumPy array

NumPy is popular scientific Python numerical computing library
and because pf this, PyTorch has functionality to interact with it.

* Data in NumPy , convert to tensor --> `torch.from_numpy(ndarray)`.

* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [44]:
import torch
import numpy as np

array = np.arange(1.0, 9.0)
tensor = torch.from_numpy(array)

In [45]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [46]:
array += 1

In [47]:
array

array([2., 3., 4., 5., 6., 7., 8., 9.])

# Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random number -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again -> again ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is 'flavour' the randomness

In [48]:
torch.rand(3,3)

tensor([[0.5089, 0.1915, 0.7458],
        [0.2291, 0.9153, 0.5146],
        [0.7943, 0.8489, 0.1249]])

In [49]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

In [50]:
print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [54]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)


print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
 !nvidia-smi


Fri Dec 20 09:09:20 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [5]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
tensor1 = torch.tensor([1,2,3], device=device)

In [8]:
print(tensor1 , tensor1.device)

tensor([1, 2, 3], device='cuda:0') cuda:0
