In [1]:
import torch
from torch import nn
import matplotlib.pyplot as plt


torch.__version__

'2.5.1+cu121'

In [2]:
weight = 0.7
bias = 0.3

start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim = 1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [3]:
class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, dtype = torch.float), requires_grad = True)

    self.bias = nn.Parameter(torch.randn(1, dtype = torch.float), requires_grad = True)


  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

PyTorch tensors created using torch.Tensor()

In [5]:
scalar.item()

7

In [7]:
vector = torch.Tensor([7,7])
vector

tensor([7., 7.])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.Tensor([[7,8],
                       [7,8]])

MATRIX

tensor([[7., 8.],
        [7., 8.]])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.Tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to represent the data

In [19]:
random_tensor = torch.rand(3,4)

In [20]:
random_tensor

tensor([[0.8561, 0.4511, 0.4823, 0.1041],
        [0.2941, 0.9502, 0.1082, 0.0341],
        [0.8395, 0.7532, 0.3593, 0.1586]])

In [22]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones * random_tensor

tensor([[0.8561, 0.4511, 0.4823, 0.1041],
        [0.2941, 0.9502, 0.1082, 0.0341],
        [0.8395, 0.7532, 0.3593, 0.1586]])

In [27]:
random_tensor.dtype

torch.float32

In [28]:
ones.dtype

torch.float32

In [29]:
torch.range(0,10)

<ipython-input-29-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
onetoten = torch.arange(1,11)

In [32]:
onetoten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
ten_zeros = torch.zeros_like(input=onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype = torch.float64,
                            requires_grad = False,
                            device = None)
float_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [43]:
float_16_tensor = float_tensor.type(torch.float16)

In [44]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [46]:
float_16_tensor.device

device(type='cpu')

In [47]:
def get_tensor_dets(tensor):
  print(tensor)
  print(f"Datatype of tensor: {tensor.dtype}")
  print(f"Shape of tensor: {tensor.shape}")
  print(f"Device tensor is on: {tensor.device}")

In [48]:
get_tensor_dets(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3])
Device tensor is on: cpu


In [49]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5761, 0.0499, 0.4864, 0.0394],
        [0.2926, 0.9895, 0.8913, 0.0449],
        [0.8646, 0.0700, 0.7830, 0.4148]])

In [50]:
random_tensor + 10

tensor([[10.5761, 10.0499, 10.4864, 10.0394],
        [10.2926, 10.9895, 10.8913, 10.0449],
        [10.8646, 10.0700, 10.7830, 10.4148]])

In [52]:
T1 = random_tensor * 10

In [53]:
random_tensor * T1

tensor([[3.3184, 0.0249, 2.3656, 0.0155],
        [0.8559, 9.7918, 7.9446, 0.0202],
        [7.4757, 0.0490, 6.1312, 1.7202]])